networks:
  schach:
    name: schach

services:
  # service 1
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: backend
    networks:
      - schach
    image: backend:latest
    ports:
      - 2222:2222
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432

  # service 2
  nginxdev:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginxdev
    container_name: nginxdev
    image: nginx:dev
    ports:
      - 1234:80
    depends_on:
      - backend

  # service 3
  tui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BACKEND_URL: localhost:2222
      target: tui
    container_name: tui
    image: tui:latest
    environment:
      BACKEND_API: localhost:2222
    depends_on:
      - backend
    ports:
      - 2345:22

  # service 4
  postgres:
    image: postgres:18.3-alpine3.23
    container_name: postgres
    networks:
      - schach
    ports:
      - 5432:5432
    command: -c listen_addresses='*'
    environment:
      POSTGRES_DB: chess
      POSTGRES_PASSWORD: password
    volumes:
      - ./apps/backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
