events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;

    # Backend
    server {
        listen 80;
        listen [::]:80;

        server_name schach-backend.walrus.codes;

        location / {
            # Forward requests to the backend server
            proxy_pass http://localhost:2222;

            # Forward original client headers
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }

    # Frontend
    server {
        listen 80;
        listen [::]:80;
        server_name schach.walrus.codes;

        location / {
            root  /var/www/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }
    }

    # Default
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name _;

        location / {
            root  /var/www/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

    }
}
