name: "Deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy_backend:
    name: "Deploy the new backend"

    runs-on: ubuntu-latest
    steps:
        - name: Deploy via SSH
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: walrus.codes
            username: admin
            key: ${{ secrets.SSH_KEY }}
            port: 4321
            script: |
              cd /home/admin/projects/schach
              bash .github/.scripts/deploy.sh
  deploy_tui:
    name: "Deploy the new TUI with key"

    runs-on: ubuntu-latest
    steps:
        - name: Deploy TUI via SSH
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: walrus.codes
            username: admin
            key: ${{ secrets.SSH_KEY }}
            port: 4321
            script: |
              mkdir -p /home/admin/projects/schach/src/tui/.ssh
              echo "${{ secrets.TUI_KEY }}" > /home/admin/projects/schach/src/tui/.ssh/tui.key
              cd /home/admin/projects/schach
              bash .github/.scripts/deploy.sh
